# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3920a02b103d343dc65f91d12649cf6c3ddc75a356749d8322bf063e52c75a8eae4eff8ae9865fc9eadef3153f8e41b88e8b677a3e9d4a2ec3b43341341efec6

test:
  secret_key_base: c1d6fce0f779212dab762891fb2404f0752af3d6bdba8878cff4fd0ca2602361063d5a6780049644e20e0d4e69dc6b5bf4785123b099ba8db9ec2f88cc7d27c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
